// AUTO-GENERATED by `bun run bake:combos`. Do not edit by hand.
//
// The set of combo keys (see lib/combo.ts) that have a baked GLB uploaded to
// R2 under models/combos/<key>.glb. The AR seam (lib/ar.ts) only points Scene
// Viewer at a combo when its key is in this set; otherwise it falls back to the
// base dish model. Empty until component (side/add-on) GLBs exist to bake.

export const BAKED_COMBOS: ReadonlySet<string> = new Set<string>([]);
